#!groovy

//@Library('functions')_

pipeline {
	agent any // Default Agent

  
  stages {

    stage('Init') {
    	
      steps {
      	sh 'docker ps'
      }
    }
    
    stage('Test') {
      // Specifies where the entire Pipeline, or a specific stage, will execute in the Jenkins environment depending on where the agent section is placed
    	agent {
      	docker {
        	image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
      	sh 'mvn test'
      }
    }

    

  }

  post {
    always  {
      sh 'docker logout'
      
    }
    success {
      echo "SUCCESS"
    }
  }
  
}


def getLastGitTag() {
    sh "git tag --sort version:refname | head -n 1 > version.tmp"
    String tag = readFile 'version.tmp'
    echo "Branch: ${scm.branches[0].name}"
    echo "Tag, ${tag}." 
    return tag
}
